### ISSUE TITLE
padding: none;

### ISSUE THREAD

**Issue by alexgleason** [liberationphilly/liberationphilly.org#24]
`padding: none;` 3 results found
`margin: none;` 2 results found

These properties are currently doing nothing, because `none` is an invalid value. Clearly they were intended to do something, probably to set the padding and margin to `0`, but they aren't. If you're happy with the way the CSS works currently, you can just remove those lines since they do nothing. But if you want those spots to actually remove padding, you will need to set them to `0`.

(note: you can use `0` rather than `0px` because the property accepts any value of measurement, such as `5in`, `22cm`, `7em`; and `0` means "zero of any unit")

**Comment by marykatefain** [comment]
Thanks! We can just remove the lines since apparently I worked around it at some point haha. Unless you're bored enough to one by one review them and see if there is a better way to do it. I may have had to do some dumb hack to account for my mistake so... Feel free to fix and un-hack, otherwise I will delete those lines!
